"""
Django settings for ecommerceHardcoregamesBack project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os

import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',')]

# CORS_ALLOWED_ORIGINS = {
#  'http://localhost:4200',
# }

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     'http://localhost:4200',
# ]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    'http://localhost',
    'http://localhost:4200'
)

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'users',
    'products',
    'rewards',
    'sorteos',
]

JAZZMIN_SETTINGS = {
        "site_title": "HardcoreGames Admin",
        "site_header": "HardcoreGames",
        "site_brand": "HardcoreGames",
        "welcome_sign": "Bienvenido al panel de administracion",
        "copyright": "HardcoreGames",
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Sitio", "url": "https://www.hardcoregames.co", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "products.Products": "fas fa-gamepad",
        "products.ProductAccounts": "fas fa-key",
        "products.SaleDetail": "fas fa-shopping-cart",
        "products.Consoles": "fas fa-tv",
        "products.TypeGames": "fas fa-tags",
        "products.VariablesSistema": "fas fa-cogs",
        "products.Licenses": "fas fa-certificate",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
}
MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'ecommerceHardcoregamesBack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerceHardcoregamesBack.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DB_NAME', 'hardcoregames_ueh3'),
        'USER': os.environ.get('DB_USER', 'hardcoregames_ueh3_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'hc-postgres'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

#DATABASES["default"] = dj_database_url.parse("postgres://hardcoregames_user:2q8EyqLkflfpSjtMfAkAphoThSmkDy1V@dpg-ckhfi94ldqrs73a4kc3g-a.oregon-postgres.render.com/hardcoregames")

# Cache compartido entre workers de Gunicorn (LocMemCache falla con --workers > 1)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_URL_FILES = 'static/files/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SEND_EMAIL = os.environ.get('SEND_EMAIL', '')
# FROM_EMAIL="ventas@hardcoregames.co"
FROM_EMAIL = os.environ.get('FROM_EMAIL', 'jhoan0498@gmail.com')
# PASS_SMTP="udeu fewe jbof sckp "
PASS_SMTP = os.environ.get('PASS_SMTP', '')
SUBJECT_EMAIL_FOR_TOKEN = "Código para cambio de contraseña HardCoreGames"
SUBJECT_EMAIL_FOR_SALE = "Pedido digital en Hardcore Games"
EMAIL_FOR_TOKEN = "<html>" \
                    "<body>" \
                        "<h2>Solicitud de nueva contraseña HardCoreGames</h2><br>" \
                        "<justify>Está recibiendo este correo electrónico porque se ha solicitado un cambio de contraseña para la cuenta de HardCoreGames. " \
                        "Su codigo de activacion para cambio de contraseña es:</justify> " \
                    "</body>" \
                  "</html>"

EMAIL_FOR_SALE = '<!DOCTYPE html> <html lang="es"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta name="color-scheme" content="light dark"> <title>Hardcore Games – Confirmación de Compra</title> <style> @media only screen and (max-width: 620px) { .wrapper { width: 100% !important; } .content-pad { padding: 20px 16px !important; } } @media (prefers-color-scheme: dark) { .email-bg { background-color: #080c14 !important; } } </style> </head> <body style="margin:0;padding:0;background-color:#080c14;font-family:Arial,Helvetica,sans-serif;"> <!-- Preheader --> <span style="display:none;font-size:1px;color:#080c14;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">Tu pedido está listo — aquí tienes los datos de acceso a tu producto. ¡Gracias por comprar en Hardcore Games!</span> <!-- Outer wrapper --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#080c14;"> <tr> <td align="center" style="padding:40px 10px;"> <!-- Card --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" class="wrapper" style="max-width:600px;background-color:#0d1220;border-radius:8px;border:1px solid #1a2a4a;overflow:hidden;"> <!-- TOP ACCENT BAR --> <tr> <td style="height:3px;background:linear-gradient(90deg,#00d4ff 0%,#7b2fff 50%,#00d4ff 100%);font-size:0;line-height:0;">&nbsp;</td> </tr> <!-- HEADER --> <tr> <td align="center" style="padding:36px 30px 28px;background-color:#0d1220;"> <!-- Hex grid decoration top-left via border trick --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td align="center"> <!-- Logo --> <img src="https://www.hardcoregames.co/assets/logo-CYf73ajV.png" width="180" alt="Hardcore Games" style="display:block;border:0;max-width:180px;"> </td> </tr> <tr> <td align="center" style="padding-top:20px;"> <!-- Tagline chip --> <table role="presentation" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="background-color:#00d4ff14;border:1px solid #00d4ff55;border-radius:4px;padding:4px 14px;"> <span style="font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#00d4ff;letter-spacing:3px;text-transform:uppercase;">Confirmación de Compra</span> </td> </tr> </table> </td> </tr> </table> </td> </tr> <!-- DIVIDER --> <tr> <td style="padding:0 30px;"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td style="height:1px;background-color:#1a2a4a;font-size:0;line-height:0;">&nbsp;</td> </tr> </table> </td> </tr> <!-- HERO MESSAGE --> <tr> <td style="padding:32px 36px 24px;" class="content-pad"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td> <h1 style="margin:0 0 16px;font-family:Arial,Helvetica,sans-serif;font-size:28px;font-weight:700;color:#ffffff;line-height:1.2;">¡Gracias por tu compra!</h1> <p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:15px;color:#8a9bb8;line-height:1.6;"> Hemos recibido tu pedido. A continuación encontrarás los datos de acceso necesarios para obtener tu producto. </p> </td> </tr> </table> </td> </tr> <!-- ACCESS DATA BOX --> <tr> <td style="padding:0 36px 32px;" class="content-pad"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#0a1628;border:1px solid #1a3a6a;border-radius:6px;"> <!-- Box header --> <tr> <td style="padding:12px 20px;background-color:#0f1e38;border-radius:6px 6px 0 0;border-bottom:1px solid #1a3a6a;"> <table role="presentation" cellpadding="0" cellspacing="0" border="0"> <tr> <td style="width:8px;height:8px;background-color:#00d4ff;border-radius:50%;font-size:0;">&nbsp;</td> <td style="width:6px;">&nbsp;</td> <td style="width:8px;height:8px;background-color:#7b2fff;border-radius:50%;font-size:0;">&nbsp;</td> <td style="width:6px;">&nbsp;</td> <td style="width:8px;height:8px;background-color:#1a3a6a;border-radius:50%;font-size:0;">&nbsp;</td> <td style="padding-left:12px;font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#c8daea;letter-spacing:1px;">Credenciales de producto</td> </tr> </table> </td> </tr> <!-- Box content --> <tr> <td id="body" style="padding:24px 20px;font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#8a9bb8;line-height:1.8;"> <span style="color:#00d4ff;">&#9658;</span>&nbsp;Tus claves y credenciales aparecerán aquí cuando el sistema procese tu pedido.<br> <span style="color:#00d4ff;">&#9658;</span>&nbsp;Guarda este correo como respaldo de tu licencia.<br> <span style="color:#7b2fff;">&#9658;</span>&nbsp;Puedes ver esta y todas tus compras en:<br><br> <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin-top:4px;"><tr><td align="center" style="background-color:#7b2fff;border-radius:5px;padding:10px 22px;"><a href="https://www.hardcoregames.co/purchases" style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#ffffff;text-decoration:none;font-weight:700;letter-spacing:0.5px;" target="_blank">Ver mis compras &#8594;</a></td></tr></table> </td> </tr> </table> </td> </tr> <!-- SIGN-OFF --> <tr> <td style="padding:0 36px 32px;" class="content-pad"> <p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#8a9bb8;line-height:1.6;"> — Equipo <span style="color:#ffffff;font-weight:700;">Hardcore Games</span> </p> <p style="margin:10px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#c8daea;line-height:1.6;"> ¿Dudas sobre garantías o funcionamiento? <a href="https://www.hardcoregames.co/help" style="color:#00d4ff;text-decoration:none;" target="_blank">Visita nuestro centro de ayuda &#8599;</a> </p> </td> </tr> <!-- DIVIDER --> <tr> <td style="padding:0 30px;"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td style="height:1px;background-color:#1a2a4a;font-size:0;line-height:0;">&nbsp;</td> </tr> </table> </td> </tr> <!-- INSTALLATION GUIDES --> <tr> <td style="padding:28px 36px 32px;" class="content-pad"> <p style="margin:0 0 20px;font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#00d4ff;letter-spacing:2px;text-transform:uppercase;">// Guías de instalación</p> <!-- Xbox / PC --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-bottom:20px;"> <tr> <td style="background-color:#0a1628;border:1px solid #1a3a6a;border-radius:6px;padding:18px 20px;"> <p style="margin:0 0 14px;font-family:Arial,Helvetica,sans-serif;font-size:13px;font-weight:700;color:#ffffff;letter-spacing:0.5px;">&#9632; Xbox &amp; PC</p> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr><td style="padding-bottom:10px;"><span style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#c8daea;">Licencia primaria&nbsp;&nbsp;</span><a href="https://youtu.be/7zrgXHX8M9A" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00d4ff;text-decoration:none;font-weight:700;" target="_blank">&#9654; Ver tutorial</a></td></tr> <tr><td style="padding-bottom:10px;"><span style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#c8daea;">Licencia secundaria&nbsp;&nbsp;</span><a href="https://youtu.be/oRxxv08attg" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00d4ff;text-decoration:none;font-weight:700;" target="_blank">&#9654; Ver tutorial</a></td></tr> <tr><td style="padding-bottom:10px;"><span style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#c8daea;">Licencia PC&nbsp;&nbsp;</span><a href="https://www.youtube.com/watch?v=Q2VhD64uSVU" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00d4ff;text-decoration:none;font-weight:700;" target="_blank">&#9654; Ver tutorial</a></td></tr> <tr><td><span style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#c8daea;">Instalar juegos en Xbox&nbsp;&nbsp;</span><a href="https://www.youtube.com/watch?v=4TDpSrJ0aqM" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00d4ff;text-decoration:none;font-weight:700;" target="_blank">&#9654; Ver tutorial</a></td></tr> </table> </td> </tr> </table> <!-- PS4 / PS5 --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td style="background-color:#0a1628;border:1px solid #1a3a6a;border-radius:6px;padding:18px 20px;"> <p style="margin:0 0 14px;font-family:Arial,Helvetica,sans-serif;font-size:13px;font-weight:700;color:#ffffff;letter-spacing:0.5px;">&#9632; PS4 &amp; PS5</p> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr><td><span style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#c8daea;">Instalación por QR&nbsp;&nbsp;</span><a href="https://youtu.be/_qxBMg2tWmc?t=30" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00d4ff;text-decoration:none;font-weight:700;" target="_blank">&#9654; Ver tutorial</a></td></tr> </table> </td> </tr> </table> </td> </tr> <!-- DIVIDER --> <tr> <td style="padding:0 30px;"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td style="height:1px;background-color:#1a2a4a;font-size:0;line-height:0;">&nbsp;</td> </tr> </table> </td> </tr> <!-- SUPPORT SECTION --> <tr> <td style="padding:28px 36px;" class="content-pad"> <p style="margin:0 0 16px;font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#00d4ff;letter-spacing:2px;text-transform:uppercase;">// Soporte</p> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <!-- Email --> <td width="50%" valign="top"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="background-color:#0a1628;border:1px solid #1a3a6a;border-radius:6px;width:100%;"> <tr> <td style="padding:14px 16px;"> <p style="margin:0 0 4px;font-family:Arial,Helvetica,sans-serif;font-size:10px;color:#c8daea;letter-spacing:1px;text-transform:uppercase;">Email</p> <a href="mailto:hardcorgamesx@gmail.com" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00d4ff;text-decoration:none;" target="_blank">hardcorgamesx@gmail.com</a> </td> </tr> </table> </td> <td width="12" style="font-size:0;">&nbsp;</td> <!-- WhatsApp --> <td width="50%" valign="top"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="background-color:#0a1628;border:1px solid #1a3a6a;border-radius:6px;width:100%;"> <tr> <td style="padding:14px 16px;"> <p style="margin:0 0 4px;font-family:Arial,Helvetica,sans-serif;font-size:10px;color:#c8daea;letter-spacing:1px;text-transform:uppercase;">WhatsApp</p> <a href="https://wa.link/y72sz9" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;color:#00ff88;text-decoration:none;" target="_blank">+57 324 725 9150</a> </td> </tr> </table> </td> </tr> </table> <!-- Promo channel button --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-top:14px;"> <tr> <td align="center" style="background-color:#00ff8814;border:1px solid #00ff8844;border-radius:6px;padding:12px;"> <a href="https://chat.whatsapp.com/JtGaoogjxrKF5eo54sbMYT" style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#00ff88;text-decoration:none;font-weight:700;" target="_blank"> &#9889; Únete a nuestro canal de promociones en WhatsApp </a> </td> </tr> </table> <!-- News channel button --> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin-top:10px;"> <tr> <td align="center" style="background-color:#00d4ff14;border:1px solid #00d4ff44;border-radius:6px;padding:12px;"> <a href="https://whatsapp.com/channel/0029Va0NflMBKfi45Z51UP39" style="font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#00d4ff;text-decoration:none;font-weight:700;" target="_blank"> &#127881; Únete a nuestro canal de noticias y sorteos GRATIS </a> </td> </tr> </table> </td> </tr> <!-- BOTTOM ACCENT BAR --> <tr> <td style="height:3px;background:linear-gradient(90deg,#00d4ff 0%,#7b2fff 50%,#00d4ff 100%);font-size:0;line-height:0;">&nbsp;</td> </tr> <!-- FOOTER --> <tr> <td style="padding:20px 36px;background-color:#080c14;" class="content-pad"> <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"> <tr> <td align="center"> <p style="margin:0 0 6px;font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#2a3a5a;">Copyright &copy; 2026 Hardcore Games. Todos los derechos reservados.</p> <p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:11px;color:#2a3a5a;"> <a href="https://www.hardcoregames.co/help" style="color:#2a3a5a;text-decoration:underline;" target="_blank">Cancelar suscripción</a> &nbsp;&middot;&nbsp; Colombia </p> </td> </tr> </table> </td> </tr> </table> <!-- /Card --> </td> </tr> </table> </body> </html>'


# --- Logging: con DEBUG=False Django no manda las excepciones a la consola.
# Sin esto, un 500 no aparece en `docker logs hc-django`.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Sesiones persistentes
SESSION_COOKIE_AGE = 31536000
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Mismo secreto de firma de JWT que usa hc-fastapi, copiado bajo otro nombre
# para verificar en Django (sin llamada de red) el Bearer token que manda
# el frontend a salesByUser. Ver settings.py para el mismo cambio.
FASTAPI_JWT_SECRET_KEY = os.getenv("FASTAPI_JWT_SECRET_KEY")
